<?php

declare(strict_types=1);
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;


/**
 * @file
 * Primary module hooks for sharjah_dd module.
 */



/**
 * Implements hook_theme().
 */
function sharjah_dd_theme($existing, $type, $theme, $path)
{

  return [
    'header' => [
      'variables' => ['items' => NULL],
      'template' => 'header',
    ],
    // home_banner
    'home_banner' => [
      'variables' => ['items' => NULL],
      'template' => 'home-banner',
    ],
  // performance_highlights
    'performance_highlights' => [
      'variables' => ['items' => NULL],
      'template' => 'performance-highlights',
    ],
    // front-services.html.twig
    'front_services' => [
      'variables' => ['items' => NULL],
      'template' => 'front-services',
    ],
    // front_initiatives
    'front_initiatives' => [
      'variables' => ['items' => NULL],
      'template' => 'front-initiatives',
    ],
    // front_latest_news
    'front_latest_news' => [
      'variables' => ['items' => NULL],
      'template' => 'front-latest-news',
    ],
      // footer
    'footer' => [
      'variables' => ['items' => NULL],
      'template' => 'footer',
    ],
    // about
    'about' => [
      'variables' => ['items' => NULL],
      'template' => 'about',
    ],
    'header_title_block' => [
      'variables' => [
        'items' => [],
      ],
    ],
    
  ];
}   


/**
 * Implements hook_form_alter().
 *
 * This function alters the exposed filter forms for the services view.
 */
function sharjah_dd_form_alter(&$form, FormStateInterface $form_state, $form_id)
{

  // if ($form['#id'] === 'views-exposed-form-services-main-page') {
  //   $url = Url::fromRoute('view.services.main_page', [], [
  //     'fragment' => 'services',
  //     // 'query' => \Drupal::request()->query->all(), // keep current query if needed
  //   ]);
  //   $form['#action'] = $url->toString();
  
  //   if (isset($form['keys'])) {
  //     $form['keys']['#name'] = 'title'; // rename GET param
  //   }
  // }

  // if ($form['#id'] === 'views-exposed-form-services-list') {
  //   $url = Url::fromRoute('sharjah_dd.front', [], [
  //     'fragment' => 'services',
  //     // 'query' => \Drupal::request()->query->all(), // keep current query if needed
  //   ]);
  //   $form['#action'] = $url->toString();
  
  //   if (isset($form['keys'])) {
  //     $form['keys']['#name'] = 'title'; // rename GET param
  //   }
  // }
  
}

