<?php

declare(strict_types=1);
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\config_pages\Entity\ConfigPages;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;

/**
 * @file
 * Primary module hooks for sharjah_dd module.
 */



/**
 * Implements hook_theme().
 */
function sharjah_dd_theme($existing, $type, $theme, $path)
{

  return [
    'header' => [
      'variables' => ['items' => NULL],
      'template' => 'header',
    ],
    // home_banner
    'home_banner' => [
      'variables' => ['items' => NULL],
      'template' => 'home-banner',
    ],
  // performance_highlights
    'performance_highlights' => [
      'variables' => ['items' => NULL],
      'template' => 'performance-highlights',
    ],
    // front-services.html.twig
    'front_services' => [
      'variables' => ['items' => NULL],
      'template' => 'front-services',
    ],
    // front_initiatives
    'front_initiatives' => [
      'variables' => ['items' => NULL],
      'template' => 'front-initiatives',
    ],
    // front_latest_news
    'front_latest_news' => [
      'variables' => ['items' => NULL],
      'template' => 'front-latest-news',
    ],
      // footer
    'footer' => [
      'variables' => ['items' => NULL],
      'template' => 'footer',
    ],
    // about
    'about' => [
      'variables' => ['items' => NULL],
      'template' => 'about',
    ],
    'header_title_block' => [
      'variables' => [
        'items' => [],
      ],
    ],
    // looking_digital_service  
    'looking_digital_service' => [
      'variables' => ['items' => NULL],
      'template' => 'looking-digital-service',
    ],
    
  ];
}   


/**
 * Implements hook_form_alter().
 *
 * This function alters the exposed filter forms for the services view.
 */
function sharjah_dd_form_alter(&$form, FormStateInterface $form_state, $form_id)
{

  if (isset($form['field_year'])) {
    $form['field_year']['#attributes']['class'][] = 'only-wrapper-hidden hidden';
  
  }
  // echo "<pre>";
  // print_r($form['#id']);
  // echo "</pre>";
  if($form['#id'] =='simplenews-subscriptions-block-0b9add7d-f918-4fe8-ba20-9f98cacb0143')
  {
  
    $form['#attributes']['class'][] = 'my-custom-form w-full newsletter-form';
    // Add a class to a specific input, for example the email field.
    if (isset($form['mail'])) {

      $form['mail']['widget'][0]['value']['#attributes']['class'][] = 'gradient-text block min-h-[50px] w-full rounded-2xl bg-white outline-0';
      $input = $form['mail'];
      $form['mail']['widget'][0]['value']['#attributes']['placeholder'] = t('Enter your email');
      
      $form['mail']['#prefix'] = '<div class="mt-7 flex w-full max-w-[470px] items-center justify-between gap-3 rounded-2xl bg-white p-3 ps-6">';
      $form['actions']['#suffix'] = '</div>';
    }

    // Add a class to the submit button.
    if (isset($form['actions']['submit'])) {
      $form['actions']['submit']['#attributes']['class'][] = 'btn btn-primary rounded-[10px] bg-[#353535] p-2 font-bold text-white md:p-6';
    }
  }


  
}

/**
 * Implements hook_preprocess_HOOK() for webform submission form.
 */
function sharjah_dd_preprocess_webform_submission_form(array &$variables) {
  

  $config_page = ConfigPages::config('general_pages');
  if (!$config_page) {
    return [];
  }
  
  $phone = $config_page->get('field_c_phone_number')->value ?? '';
  $email = $config_page->get('field_c_email_us')->value ?? '';
  $working_hours = $config_page->get('field_c_working_hours')->getValue();
  $working_hours1 = $working_hours[0]['value'] ?? '';
  $working_hours2 = $working_hours[1]['value'] ?? '';

  $addresses = $config_page->get('field_c_address')->getValue();
  $address1 = $addresses[0]['value'] ?? '';
  $address2 = $addresses[1]['value'] ?? '';

  $form_image = $config_page->get('field_contact_image')->entity ?? '';

  $form_img_url = '';
  if ($form_image instanceof \Drupal\file\FileInterface) {
    $form_img_url = \Drupal::service('file_url_generator')->generateAbsoluteString($form_image->getFileUri());
  }
  
  // pass in array 
  $variables['contact_info'] = [
    'working_hours' => [
      'working_field1' => $working_hours1,
      'working_field2' => $working_hours2],
    'addresses' => [$address1 , $address2],
    'phone' => $phone,
    'email' => $email,
    'form_image' => $form_img_url,
  ];
  
}



/**
 * Implements hook_entity_presave().
 */
function sharjah_dd_entity_presave(EntityInterface $entity) {
  if (!$entity instanceof NodeInterface) {
    return;
  }

  // Limit to specific bundles (add more if needed).
  $bundles = ['our_journey','news'];
  if (!in_array($entity->bundle(), $bundles, true)) {
    return;
  }
  if ($entity->hasField('field_year')) {
    $year = (int) \Drupal::service('date.formatter')->format($entity->getCreatedTime(), 'custom', 'Y');
// dd("test");
    // If it's a List (text) field, save as string; otherwise integer is fine.
    $definition = $entity->getFieldDefinition('field_year')->getFieldStorageDefinition();
    $is_list_text = $definition->getType() === 'list_string' || $definition->getType() === 'list_text';

    $entity->set('field_year', $is_list_text ? (string) $year : $year);
  }
}
